apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-apps
spec:
  project: default
  source:
    repoURL: https://github.com/schwesig/gitops_local.git
    path: my-app
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
